OPENSSLSNIPPETS_LICENSE = Barco
OPENSSLSNIPPETS_VERSION = HEAD
OPENSSLSNIPPETS_SITE = /home/lodco/misc/openssl-snippets/
OPENSSLSNIPPETS_SITE_METHOD = local
OPENSSLSNIPPETS_INSTALL_STAGING = YES
OPENSSLSNIPPETS_INSTALL_TARGET = NO

define OPENSSLSNIPPETS_BUILD_CMDS 
  $(MAKE) CC="$(TARGET_CC)" LD="$(TARGET_LD)" -C $(@D) generate_priv_key
endef

$(eval $(generic-package))
